### ISSUE TITLE
Aydınlatma

### ISSUE THREAD

**Issue by MoonstoneLight** [dnzprmksz/moodify#39]
WebTekno'dan geliyorum.
Spotify'da her yılın sonunda hangi şarkıyı toplam ne kadar dinlediğini gösteren bir özellik var ve sadece Premium kullanıcılar için geçerli. Sitenizin alt kısmında Şimdilerde, Önceden Dinledikleriniz şeklinde kısımlar var fakat Long Time Ago, Months Earlier ve Nowadays Kısımlarının tam olarak belirttiği zaman dilimini söyleyebilir misiniz? 
Teşekkürler ve Saygılar...

**Comment by dnzprmksz** [comment]
Merhaba @MoonstoneLight, sırasıyla aşağı yukarı Spotify kullanımı boyunca, 3-4 ay önce ve son birkaç hafta gibi bir aralığa tekabül ediyorlar.
