### ISSUE TITLE
Bug on The Website

### ISSUE THREAD

**Issue by MoonstoneLight** [dnzprmksz/moodify#40]
Hi,
I was logged in yesterday and I tried to create a Playlist. It said First, Create Playlist - Wait - Check Spotify. But it didn't create anything. I am trying again today and there isn't anything on the website. Screen Photos are here:
https://drive.google.com/file/d/1vGdHvfGupVDBZq_CPEWn0sONJXDy2fXH/view?usp=sharing
https://drive.google.com/file/d/1dcUI1PGgHk7mgfGo4Q_vIj7bP8tpcXES/view?usp=sharing
https://drive.google.com/file/d/1RRDafggwp4-izurNt-zNrfZxmTqb-XVT/view?usp=sharing

**Comment by dnzprmksz** [comment]
@MoonstoneLight Turns out there was a bug on web app that makes it fail after Spotify token expires, which happens a month later after you give permission. That's why it took some time to spot the bug.
Fixed by https://github.com/dnzprmksz/moodify/pull/41
